api:
  extends:
    file: ./docker-compose.api.yml
    service: api
  links:
    - redis:redis.link
    - postgres:postgres.link

redis:
  extends:
    file: ./docker-compose.api.yml
    service: redis

postgres:
  extends:
    file: ./docker-compose.api.yml
    service: postgres
